repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: check-json
- repo: https://github.com/psf/black
  rev: 19.3b0
  hooks:
  - id: black
- repo: https://github.com/asottile/seed-isort-config
  rev: v1.9.3
  hooks:
  - id: seed-isort-config
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
  hooks:
  - id: isort
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: "v0.770"  # Use the sha / tag you want to point at
  hooks:
  - id: mypy
    args: [--no-strict-optional, --ignore-missing-imports]
- repo: https://github.com/pycqa/pydocstyle
  rev: 5.0.2  # pick a git hash / tag to point to
  hooks:
  - id: pydocstyle
- repo: https://gitlab.com/pycqa/flake8
  rev: "3.7.9"  # pick a git hash / tag to point to
  hooks:
  - id: flake8